### PR TITLE
Add @matheuscscp to core maintainers

### PR DESCRIPTION
**Pull request by matheuscscp**
In my new position I can dedicate a lot of time to Flux development and my personal goal is to make the question "what GitOps tool should I choose for my Kubernetes cluster?" as trivial as it for me to everybody else in the world :)

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
+1 Thanks @matheuscscp for all the hard work so far 🥇

**Review by makkes — APPROVED** [review]

**Review by hiddeco — APPROVED** [review]

**Comment by makkes** [comment]
I just went through our [process doc](https://github.com/fluxcd/community/blob/main/PROCESS.md#applying-for-flux-maintainership) on this and there's a couple of things to take into account:

- [x] mention all maintainers: @relu @hiddeco @makkes @pjbgf @aryan9600 @souleb @stefanprodan @darkowlzz 
- [ ] Have maintainers submit their vote by +1

**Comment by makkes** [comment]
+1

**Comment by stefanprodan** [comment]
Approving the PR is the same as commenting with +1. But yes we need two more!

**Review by pjbgf — APPROVED** [review]
+1

**Comment by souleb** [comment]
+1

**Comment by aryan9600** [comment]
+1 from me!

**Review by aryan9600 — APPROVED** [review]

**Comment by stefanprodan** [comment]
We have unanimity, thanks everyone and a big welcome to Matheus 🎉

**Comment by matheuscscp** [comment]
:pray: :raised_hands: :sob: :rocket:

**Pull request merged**
