### PR TITLE
Add myself to maintainers list

### PR DESCRIPTION
**Pull request by alisondy**
Signed-off-by: Alison Dowdney <alison@alisondowdney.com>

### CODE REVIEW

**Review by dholbach — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]
✨ ✨ ✨

**Review by scottrigby — APPROVED** [review]
🙂

**Comment by dholbach** [comment]
We discussed a lazy consensus and mail to `f-maintainers` in the meeting earlier ... @alisondy right?

**Comment by stefanprodan** [comment]
Looks like @scottrigby wasn't aware...

**Comment by scottrigby** [comment]
I guess I was too excited 😉 

OK I wasn't aware an email was discussed. Our governance process just needs consensus for this [team and repo](https://github.com/fluxcd/community/blob/main/MAINTAINERS), and we unanimity in this PR so I went ahead. But that said… if you do want to do an email, all is not lost 🙂 should we revert this PR and open another one that we wait on?

**Comment by stefanprodan** [comment]
It's ok @scottrigby we can leave opened the PR for website.

**Pull request merged**
