### PR TITLE
Update maintainer data

### PR DESCRIPTION
**Pull request by fluxcdbot**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by kingdonb** [comment]
This PR adds @mewzherder to the maintainers list.

@makkes @stefanprodan You may want to look at this, as you both have conflicting details in the `rolodex.yaml` now from what I can see, and they appear to flap order here since yaml keys are duplicated, there is no deterministic order.

It looks like the different information comes from, most likely go-git-providers? There are some others that might need updating.

@yiannistri @foot

**Review by makkes — APPROVED** [review]

**Comment by stefanprodan** [comment]
I will update my affiliation everywhere, please hold this PR

**Comment by stefanprodan** [comment]
I've updated my data and it's all good now. @makkes has approved it so I guess he's fine with being listed twice.

**Review by makkes — APPROVED** [review]
I don't know why I'm turning up twice. Removed the dup.

**Comment by stefanprodan** [comment]
@makkes https://github.com/fluxcd/go-git-providers/blob/55ec353d8dd08a215eddc9ec436d8aef180847fe/MAINTAINERS#L7

**Comment by makkes** [comment]
I see. Changed that in https://github.com/fluxcd/go-git-providers/pull/263

**Pull request merged**
