### PR TITLE
add explicit permission for create-issue action

### PR DESCRIPTION
**Pull request by kingdonb**
Attempting to diagnose the actions failure here:

https://github.com/fluxcd/community/actions/runs/7856529479/job/21439398292

### CODE REVIEW

**Comment by kingdonb** [comment]
Not really sure if this will help

**Comment by kingdonb** [comment]
I read the docs for permissions and I took a look, I guess `issues: write` didn't used to be an explicit permission you had to grant. This should fix it

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @kingdonb

**Comment by kingdonb** [comment]
I guess that didn't work:

> Error: Resource not accessible by integration

https://github.com/fluxcd/community/actions/runs/8023161222/job/21938832424

**Pull request merged**
