### PR TITLE
Add markdwon-link-check on PR and cronjob

### PR DESCRIPTION
**Pull request by NissesSenap**
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>

### CODE REVIEW

**Comment by dholbach** [comment]
Do you have a link to the output of the checks that were run somewhere?

**Comment by NissesSenap** [comment]
I don't have anyone for this PR, but you can see a example here in the website repo:
Broken: https://github.com/NissesSenap/website/runs/2806263094?check_suite_focus=true

Ok: https://github.com/NissesSenap/website/runs/2806285903?check_suite_focus=true

**Comment by dholbach** [comment]
Do we maybe need to enable Github Actions for this repository first?

**Comment by NissesSenap** [comment]
There is no need for that any more, it's on by default in public repos.
It just doesn't trigger due to it's not merged. Created a PR towards my PR and sen't in some bad data to trigger an error.
You can see the output here:
https://github.com/NissesSenap/community/pull/1/checks?check_run_id=2820484500

**Comment by NissesSenap** [comment]
@dholbach I have updated the PR now, hopefully it looks okay.

**Review by dholbach — APPROVED** [review]
Nice work!

**Pull request merged**
