### PR TITLE
Fix bad link in governance/ doc

### PR DESCRIPTION
**Pull request by kingdonb**
Joining:

* https://github.com/fluxcd/source-controller/pull/1200

Closing this issue (and the related issues linked above) will enable us to add testing of internal links in the future, to prevent these types of issues on website from regressing.

### CODE REVIEW

**Comment by kingdonb** [comment]
The bad link is currently visible here:

https://deploy-preview-1573--fluxcd.netlify.app/governance/#meetings

> the [public developer meeting](https://deploy-preview-1573--fluxcd.netlify.app/governance/README.md#meetings).

**Review by makkes — APPROVED** [review]
Should we also remove the section in this repo's README.md to avoid future divergence?

**Comment by kingdonb** [comment]
I was getting link blindness, and this was the last of about 150 links I fixed yesterday... I didn't even think to look for it there 😂

Maybe we should just link directly to that, with an absolute link?

**Comment by kingdonb** [comment]
There, that will fix it just as well. No, I do think we should leave the README intact in the community repo

The goal of these PRs was only to fix links with minimal structural changes. If you find any links I've replaced in fluxcd/website#1573 or friends had a more direct analogue, more obvious intended target than whatever I've corrected the links to point at, let's use that instead.

**Pull request merged**
