### PR TITLE
Add Soule BA to CORE-MAINTAINERS

### PR DESCRIPTION
**Pull request by souleb**
I would like to become a core maintainer.

Signed-off-by: souleb <soule@weave.works>

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
Thanks @souleb for all your contributions on Flux. I'm very happy to have you part of the core team 🎉

**Review by hiddeco — APPROVED** [review]
Thanks for your continuous efforts and countless contributions @souleb :100:  :bow:

**Comment by relu** [comment]
Amazing work, @souleb, you have my stamp, keep it up! :raised_hands:

**Review by relu — APPROVED** [review]

**Review by makkes — APPROVED** [review]
Yay, thanks @souleb for all you've done in Flux so far. It's a pleasure working with you. +1

**Review by pjbgf — APPROVED** [review]
Strong +1! Thank you for all the great work, @souleb!

**Review by pjbgf — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]
💯👏 nb

**Review by phillebaba — APPROVED** [review]
:tada:

**Comment by hiddeco** [comment]
We got all the votes we need, thanks all. If you rebase @souleb, I will do the further due diligence.

**Pull request merged**
