### PR TITLE
Add DoneOps to paid support list

### PR DESCRIPTION
**Pull request by jmymy**
Signed-off-by: GitHub <noreply@github.com>

### CODE REVIEW

**Comment by dholbach** [comment]
@fluxcd/oversight-committee

**Comment by dholbach** [comment]
I'm not part of the Flux Oversight Committee, but as the Support doc says
> If your company has a track record of Flux engineering and/or support we will get you added.
Can you maybe say a few words about this?

**Comment by jmymy** [comment]
Any update?

**Comment by hiddeco** [comment]
Sorry, this likely got stuck in people their notification buzz. Can you please rebase the branch against `main` and change the commit message to: `Add DoneOps to paid support list`?

**Review by hiddeco — APPROVED** [review]

**Pull request merged**
