### PR TITLE
add Sanskar Jaiswal (@aryan9600) to CORE-MAINTAINERS

### PR DESCRIPTION
**Pull request by aryan9600**
I would like to apply for core maintainership. ping: @fluxcd/core-maintainers

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @aryan9600 for your contributions to Flux and Flagger

**Review by hiddeco — APPROVED** [review]
Long due :100:

**Review by pjbgf — APPROVED** [review]
Absolutely!

**Review by relu — APPROVED** [review]
🎉

**Review by souleb — APPROVED** [review]
🎉

**Review by phillebaba — APPROVED** [review]
:rose: :+1:

**Pull request merged**
