### PR TITLE
Ubuntu 24.04

### PR DESCRIPTION
**Pull request by kingdonb**
There is a dev container image for GitHub Actions, and it includes `ubuntu-24.04` image if you wish, and also it reproduces this issue. Our (fluxcd/community) repo has already been upgraded from `ubuntu-latest` of 22.04 to 24.04, but the fork I tested my fix on did not get it yet!

That's why we had an issue testing #426 #425 #424 #428 which all failed 🏃 👟 💨 

I will fix it in this PR, and do the upgrade explicitly so we know which image we are on while the phased rollout is underway.

### CODE REVIEW

**Comment by kingdonb** [comment]
Ref:

* https://github.com/actions/runner-images/issues/10636
* #428

**Comment by kingdonb** [comment]
I think now I've found out for sure that invoking python like `#!/usr/bin/python` is what's causing the problem.

We can upgrade all the way to Python 3.13 if we want now

Confirmed here:
* https://github.com/actions/runner-images/issues/10636

**Comment by kingdonb** [comment]
Verified again that the changes in this branch are working, here:

* https://github.com/kingdonb/community/actions/runs/12436540645

**Comment by kingdonb** [comment]
(I am going to remove the dev container because it did not turn out to be as helpful as I thought)

**Comment by kingdonb** [comment]
It was actually helpful, the dev container let me see what version of Python is the default in a new Ubuntu 24.04 with Python - but the actions-runner extra wasn't for testing github actions locally, it was for invoking github actions runners (with GitHub) on your deployed dev container. So I assume if we wanted arm64 self-hosted runners it would be useful, but for debugging a GitHub Actions in VSCode it was not so useful.

Still, a win for 👍 dev containers even if it's a loss for GHA debugging 👎 maybe there is some more intuitive way to use it that I did not see documented anywhere.

**Review by stefanprodan — APPROVED** [review]
Thanks @kingdonb 🥇

**Comment by kingdonb** [comment]
🏁 ✅ 
* https://github.com/fluxcd/community/actions/runs/12436901473

It worked!

**Pull request merged**
